name: Deploy Next.js to Namecheap Main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the version compatible with your Next.js app
      - name: Install Dependencies
        run: npm install
      - name: Build Next.js App
        run: npm run build
      - name: Deploy to Namecheap
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H server195.web-hosting.com >> ~/.ssh/known_hosts
          rsync -avz -e "ssh -p 21098" .next/ cronknlw@server195.web-hosting.com:/home/cronknlw/public_html/.next
          rsync -avz -e "ssh -p 21098" public/ cronknlw@server195.web-hosting.com:/home/cronknlw/public_html/public
          rsync -avz -e "ssh -p 21098" package.json cronknlw@server195.web-hosting.com:/home/cronknlw/public_html/
          rsync -avz -e "ssh -p 21098" next.config.js cronknlw@server195.web-hosting.com:/home/cronknlw/public_html/  # Include if you have this file
